@startuml
'https://plantuml.com/salt

salt
{
  Just plain text
  [This is my button]
  [This is my button]
  [This is my button]
  ()  Unchecked radio
  (X) Checked radio
  []  Unchecked box
  "Enter text here   "
  ^This is a droplist^
}
@enduml
