@startwbs
'https://plantuml.com/wbs-diagram

* Business Process Modelling WBS
** Launch the project
*** Complete Stakeholder Research
*** Initial Implementation Plan
** Design phase
*** Model of AsIs Processes Completed

*** Measure AsIs performance metrics
*** Identify Quick Wins
** Complete innovate phase
** Complete innovate phase


@endwbs
