@startuml
digraph foo {
  node [style=rounded]
  main_md1 [shape=note,label="Main.md"]
  main_pdf [shape=note,label="Main.pdf"]
  main_docx [shape=note,label="Main.docx"]
  child_md1 [shape=note, label="Child 1.md"]
  child_md2 [shape=note, label="Child 2.md"]
  diag_1  [shape=polygon, label="Diagram 1.md"]
  diag_2  [shape=polygon, label="Diagram 2.md"]

  main_md1 -> main_docx
  main_md1 -> main_pdf
  child_md1 -> main_md1
  child_md2 -> main_md1
  diag_2 -> child_md2
  diag_1 -> main_md1

}
@enduml
